name: Deploy to Zeabur
description: Deploy a service to Zeabur

branding:
  icon: arrow-up-circle
  color: purple

inputs:
  project_id:
    description: The project ID
    required: true
    type: string
  service_id:
    description: The service ID
    required: true
    type: string
  environment_id:
    description: The environment ID
    required: true
    type: string
  zeabur_api_key:
    description: The Zeabur API key
    required: true
    type: string

outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
